### ISSUE TITLE
this._source is undefined when OnClick Map to show coordinates

### ISSUE THREAD

**Issue by jczerosb** [slutske22/leaflet-popup-modifier#2]
I use bellow function to click anywhere on Map and show simple Popup with Coordinates

function onMapClick(e) {              
  L.popup()                           
      .setLatLng(e.latlng)            
      .setContent(e.latlng.toString())
      .openOn(mymap);               
}
mymap.on('click', onMapClick); // Assign funtion to onclick event

But I´m getting "this._source is undefined" at line
var nametag = this.options.nametag ? this.options.nametag : this._source.nametag;

Since "nametag" is used only at "removeButton.innerHTML", I made a "not too elegant" work around.

if (typeof this._source === 'undefined') {
      this.options.nametag = 'dummy'; // Set a useless nametag
    }
var nametag = this.options.nametag ? this.options.nametag : this._source.nametag;

It seems does not create any issue when this.options.nametag or this._source.nametag are defined, all others popups work fine with Edit, Save

**Comment by slutske22** [comment]
Thank you for pointing this out.  I had never tested this use case of having a popup without a source on the map with lefalet-popup-modifier installed.  I fixed it in the source code, and set a default nametag as 'popup' if a popup is added to the map with no source, and the author wants the 'removable' to be true. Not that anyone would ever need that, as a popup with no source is removed from the map as soon as it is closed.  The code is updated now - thank you!
